name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependences
        run: npm install

      - name: Build application
        run: npm run build

      - name: Unit tests
        run: npm run test:unit

      - name: Cucumber tests
        run: npm run test:cucumber
